import { PlusIcon } from 'lucide-react';
import React, { useState } from 'react';


interface PlayerModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (player: Player) => void;
}

const PlayerModal = ({ isOpen, onClose, onSave } : PlayerModalProps) => {

  const [playerName, setPlayerName] = useState('');

  const handleSave = () => {
    // TODO: teamID should be passed from parent component since team is a required field
    // TODO: id should be generated by the database and not passed from the client
    onSave({ id: "1", displayName: playerName, gamesPlayed: 0, teamId: "1" });
    setPlayerName('');
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="modal is-active">
      <div className="modal-background" onClick={onClose}></div>
      <div className="modal-card">
        <header className="modal-card-head">
          <p className="modal-card-title">Create Player</p>
          <button className="delete" aria-label="close" onClick={onClose}></button>
        </header>
        <section className="modal-card-body">
          <div className="has-text-centered mb-4">
                <PlusIcon />
        
                      </div>
          <div className="field">
            <label className="label">Name</label>
            <div className="control">
              <input 
                className="input" 
                type="text" 
                placeholder="Enter player name"
                value={playerName}
                onChange={(e) => setPlayerName(e.target.value)}
              />
            </div>
          </div>
         
        </section>
        <footer className="modal-card-foot">
          <button className="button is-success" onClick={handleSave}>Save changes</button>
          <button className="button" onClick={onClose}>Cancel</button>
        </footer>
      </div>
    </div>
  );
};

export default PlayerModal;
